### ISSUE TITLE
Shadow generator - date problem

### ISSUE THREAD

**Issue by piorkoo** [UMEP-dev/UMEP-processing#10]
When using Outdoor thermal comfort: shadow generator, the date is changed to the present date. There is no option to set specific date and save it into model.

**Comment by biglimp** [comment]
Are you referring to that the present date appears when you open the tool? If so, this is correct. Present date is shown. To change this you can e.g. put the tool in a processing model of put the tool in a batch process.

**Comment by piorkoo** [comment]
Thank you for prompt reply. The problem is in a processing model and in a batch process as well. When I try to run already saved model the date is changed to present.Pozdrawiam 
-------- Oryginalna wiadomość --------Od: biglimp ***@***.***> Data: 04.11.2021  15:56  (GMT+01:00) Do: UMEP-dev/UMEP-processing ***@***.***> DW: piorkoo ***@***.***>, Author ***@***.***> Temat: Re: [UMEP-dev/UMEP-processing] Shadow generator - date problem (Issue #10) 
Are you referring to that the present date appears when you open the tool? If so, this is correct. Present date is shown. To change this you can e.g. put the tool in a processing model of put the tool in a batch process.

**Comment by biglimp** [comment]
ok, I understand. I am not sure how to solve that. Have you tried to make date an input parameter in your processing model?

**Comment by biglimp** [comment]
Dont really know how do that but is should be just to make it available as an input for your model.

**Comment by piorkoo** [comment]
yes, the date parameter is available as an input. The problem is how to connect the parameter with shadow generator form? In the shadow generator form there is one option to set date: by the calendar.

**Comment by biglimp** [comment]
Now I see what you mean. You cannot choose time and date as inputs. I have no quick solution to this. You could run it within a script (https://umep-docs.readthedocs.io/en/latest/UMEPforProcessing.html)

**Comment by piorkoo** [comment]
thanks, I will check it.

**Comment by biglimp** [comment]
A recent update in the QGIS core made it possible to add a datetime parameter to the processings algorithms. Thus, I think I made it possible to use the date and time parameters here in an more accurate way. Please try out and see if it works. You need to use the developer version. See https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#installing-development-release-could-be-unstable on how you install.
