### ISSUE TITLE
RuntimeError: WITH FORCING FILE WITH supy

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/UMEP-processing#14]
df_forcing= sp.util.read_forcing('C:/Users/User/Desktop/SUEWS_Dublin/prepare/_2018_data_60.txt', tstep_mod=300)

Hello,
After I processed my forcing file with the met processor in  Umep and tried to add the forcing met file using the above sp util, I received the following error.

RuntimeError: **Loaded forcing files have gaps at: Int64Index([1, 2], dtype='int64'**).
 I tested era5 forcing era 5 data and that was successful. I however checked and compare the files. I found no gap in the data filed.

I have attached the met file

Can anyone kindly assist. Thank you

[_2018_data_60.txt](https://github.com/UMEP-dev/UMEP-processing/files/8967104/_2018_data_60.txt)

**Comment by sunt05** [comment]
Hi @phemiobe the data of DOY 152 are duplicated.

**Comment by phemiobe** [comment]
Yeah. thanks for letting me know. it worked .., Case closed
