### ISSUE TITLE
Is SOLWEIG updated to version v2022a?

### ISSUE THREAD

**Issue by j0lsson** [UMEP-dev/UMEP-processing#18]
Hi! 

When I run SOLWEIG from "UMEP for processing" the log file indicates that version 2021a is used: 
"This file provides run settings for the SOLWEIG run initiated at: Thu, 01 Dec 2022 12:08:26
Version: SOLWEIG v2021a"

Also, I get a small discrepancy in the output compared to when I run the "ordinary" UMEP SOLWEIG plugin, which in the log file says SOLWEIG v2022a. But I guess that is expected if it's different versions?

I tested with the Gothenburg sample data, which is attached (with output for each case). 
[Goteborg_SWEREF99_1200.zip](https://github.com/UMEP-dev/UMEP-processing/files/10132199/Goteborg_SWEREF99_1200.zip)

Thanks!

**Comment by nilswallenberg** [comment]
Hi,

Can you describe the discrepancy?

Both UMEP and UMEP Processing uses SOLWEIG v2022a. The function producing the log-file in UMEP Processing will be updated.

Cheers,
Nils

**Comment by j0lsson** [comment]
The Tmrt values differ between 0-1.5 deg (UMEP is higher). 

I found that the Ts_deg parameter for Walls in landcoverclasses_2016a.txt differs.  For UMEP it's 0.58 and for UMEP Processing it's 0.37. When I change it to the same value they both produce the same results. 

What does the parameter represent and which value do you recomend to use?

Best,

**Comment by nilswallenberg** [comment]
Thank you! It should be 0.37. I will fix it in the next update. It has to do with wall surface temperature. You can read about it in relation to equation 11 in [Lindberg et al. 2008](https://link.springer.com/article/10.1007/s00484-008-0162-7).

Cheers,
Nils

**Comment by biglimp** [comment]
Fixed.
