### ISSUE TITLE
Morphometric Calculator (grid) gives the same results for all calc.methods

### ISSUE THREAD

**Issue by DimitrisTsi** [UMEP-dev/UMEP-processing#19]
The morphometric calculator (grid) gives the same outputs no matter which calculation method is selected. I am not sure if this is related to the latest update (1.7.12) or goes back to previous versions.

**Comment by biglimp** [comment]
Thanks. You found a bug that has probably been with us for a long time. I will fix. If you need a quick fix, let me know.

**Comment by biglimp** [comment]
Fixed. Also fixed so that issues calculating wall area on irregular grid as well as issues when DEM and DSM had different NoData values.

**Comment by DimitrisTsi** [comment]
Hi!
I updated the plugin and i am afraid the issue persists, all outputs are the same regardless of the calculation method.
[Here](https://drive.google.com/drive/folders/18D-cvvkdLWYj10kPC0Im0202Mtoem3xt?usp=sharing) are the inputs and outputs for versions 1.7.12 and 1.7.13.

I also quickly tried to replicate the zd (zero-displacement height) output value of the isotropic calculation, using the zH, pai, fai, zStd values and the math that is present in the _RoughnessCalc(Roughnessmethod,zH,fai,pai,zMax,zSdev)_ function of the `RoughnessCalcFunctionV2.py` script, and could not get the same result that is given in the IMPGrid_isotropic.txt file using any of the methods. The zd value definitely does not match the _Rule of Thumb_ result (which is the default calculation method if the script does not manage to get input from the user if i am not mistaken) for zd which is zd = 0.7*zH.

**Comment by biglimp** [comment]
I cannot replicate your error. Changing from rule of thumbs and e.g. macDonald gives me different numbers for z0 and zd

**Comment by DimitrisTsi** [comment]
sorry @biglimp I messed something up during the update, i downloaded the package files again and it works as supposed to, thanks!
