### ISSUE TITLE
Output from SUEWS

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#2]
Are these files still valid? I am moving SUEWSAnalyzer over to the UMEP for Processing and I see that these are hard coded.
[SUEWS_OutputFormatOption1.txt](https://github.com/UMEP-dev/UMEP-processing/files/5981987/SUEWS_OutputFormatOption1.txt)
[SUEWS_OutputFormatOption2.txt](https://github.com/UMEP-dev/UMEP-processing/files/5981988/SUEWS_OutputFormatOption2.txt)

**Comment by sunt05** [comment]
Yes, they are.
But as we are using SuPy inside UMEP, I'm wondering if these are still needed and how we may better deal with these.

Can you point me to the code where these files are actually used?

**Comment by biglimp** [comment]
They are used to prepare the Plugin-interface in SUEWSAnalyzer on which parameters that are available for post-processing and what their units are. https://github.com/UMEP-dev/UMEP/blob/52a0f7ff9c1ac4cc92b48ee14013e8e0c1d9733d/SUEWSAnalyzer/suews_analyzer.py#L290

**Comment by sunt05** [comment]
double-checked these files are still valid; but I'm thinking we may use python `pickle`d files for easier post-processing, which  can also naturally integrate support for units (thanks to [`pandas-pint`](https://pint.readthedocs.io/en/latest/pint-pandas.html)).
Let me think how we can more elegantly deal with this.

related: https://github.com/UMEP-dev/SuPy/issues/3
