### ISSUE TITLE
installation error - jaydebeapi  module

### ISSUE THREAD

**Issue by HarshKamath** [UMEP-dev/UMEP-processing#24]
Hi,

I am getting an error during installation of UMEP for processing on Linux. The error seems to be associated with ' jaydebeapi' module installation. Please find the attached screenshot. Thanks
![umep_error](https://user-images.githubusercontent.com/55356169/230797081-847d19c2-ca73-4fc7-9bb5-04e8fbb8cec7.png)

**Comment by j3r3m1** [comment]
Hi,
Did you uninstall and reinstall the latest version of UMEP-processing ([2.0.1](https://plugins.qgis.org/plugins/processing_umep/version/2.0.1/)) ?

**Comment by MaryWP** [comment]
We have the same problem. I uninstalled everything, but still not working. After installation it asks to install non-existing python packages, which I did. But I get the error "Packages not installed. report any errors to https://github.com/UMEP-dev/UMEP/issues"

**Comment by biglimp** [comment]
I think I found the issue. Our reqs package umep-reqs point towards a specific Python package (netCDF4==1.6.1) that creates conflicts (netCDF4==1.6.1). A fix should be available soon.

**Comment by biglimp** [comment]
PyPi umep-reqs is updated to 2.0.1. Restart QGIS and see if this solves the problem.

**Comment by dpoursanidis** [comment]
The issue persist also in Windows installations.

![image](https://user-images.githubusercontent.com/8640644/231141597-973d3088-1cc3-4d26-b8a9-86df0765962a.png)

**Comment by j3r3m1** [comment]
OK well, obviously the jaydebeapi is not installed but we do not know why yet. Concerning the Windows installation, do you use the osgeo4W installation ? If so can you install the "jaydebeapi" library via a pip command ?
For that you need to start an osgeo command shell and type the following command:
> pip install jaydebeapi

**Comment by j3r3m1** [comment]
By the way, have you tried restarting QGIS ? Maybe the library has been installed but this action has not been immediadly taken into account...

**Comment by dpoursanidis** [comment]
Still remains the same even after osgeo4W (run as admin) and pip install

![image](https://user-images.githubusercontent.com/8640644/231160277-ff939c25-45f1-4ff3-b8b9-618db872ea21.png)

**Comment by biglimp** [comment]
What version of QGIS are you running? Could you also do `pip list` in your osgeo4w command prompt and paste the results here.

**Comment by dpoursanidis** [comment]
Here it is

run o-help for a list of available commands
C:\Program Files\QGIS 3.26.3>pip list
Package          Version
---------------- ----------
algopy           0.5.7
asteval          0.9.26
astropy          4.3.1
atmosp           0.2.9
catboost         1.0.5
cdsapi           0.5.1
certifi          2020.6.20
cftime           1.5.0
chardet          3.0.4
click            8.0.3
cloudpickle      2.0.0
colorama         0.4.4
coverage         5.3
cycler           0.10.0
dask             2022.1.0
decorator        4.4.2
dill             0.3.4
enpt-enmapboxapp 0.6.2
ExifRead         2.3.2
f90nml           1.3.1
fonttools        4.28.5
fsspec           2022.1.0
future           0.18.2
GDAL             3.5.1
geographiclib    1.50
graphviz         0.19.2
h5py             3.5.0
httplib2         0.18.1
idna             2.10
imageio          2.27.0
JayDeBeApi       1.2.3
Jinja2           2.11.2
joblib           1.0.1
JPype1           1.4.1
kiwisolver       1.2.0
lightgbm         3.3.2
linecache2       1.0.0
llvmlite         0.39.1
lmfit            1.0.3
locket           0.2.1
lxml             4.6.2
MarkupSafe       1.1.1
matplotlib       3.5.1
mock             4.0.2
mpmath           1.2.1
multiprocess     0.70.12.2
netCDF4          1.5.8
networkx         2.5
nose             1.3.7
nose2            0.9.2
numba            0.56.4
numdifftools     0.9.40
numexpr          2.8.1
numpy            1.20.2
OWSLib           0.25.0
packaging        20.4
pandas           1.1.3
partd            1.2.0
patsy            0.5.2
Pillow           9.1.1
Pint             0.18
pip              23.0.1
Platypus-Opt     1.0.4
plotly           4.12.0
ply              3.11
psutil           5.8.0
psycopg2-binary  2.8.6
pvlib            0.9.0
pyerfa           2.0.0
Pygments         2.7.2
pyodbc           4.0.30
PyOpenGL         3.1.5
pyparsing        2.4.7
pypiwin32        223
pyproj           3.3.1
PyQt5            5.15.4
PyQt5-sip        12.8.1
python-dateutil  2.8.1
pytz             2020.1
PyWavelets       1.4.1
pywin32          228
PyYAML           5.3.1
requests         2.24.0
retrying         1.3.3
scikit-image     0.18.3
scikit-learn     0.24.2
scipy            1.6.2
seaborn          0.11.2
setuptools       56.0.0
Shapely          1.8.0
simplejson       3.17.2
sip              6.1.1
six              1.15.0
statsmodels      0.13.1
supy             2021.11.22
supy-driver      2021a15
sympy            1.11.1
threadpoolctl    2.2.0
tifffile         2023.3.21
toml             0.10.1
toolz            0.11.2
tqdm             4.62.3
traceback2       1.4.0
typeguard        2.13.3
uncertainties    3.1.6
unittest2        1.1.0
urllib3          1.25.11
wheel            0.37.1
wxPython         4.1.1
xarray           0.20.2
xgboost          1.5.2
xlrd             1.2.0
xlwt             1.3.0

C:\Program Files\QGIS 3.26.3>

**Comment by biglimp** [comment]
thanks. Strange that you get your python error since as you have jaydebeapi installed... I think it has something to do with netCDF4. Could you please do the following:

1. While having an active QGIS session running, go to your osgeo4w command prompt and type `pip install umep-reqs`
2. if the command above gave you error, paste it here and then close your QGIS session and retype `pip install umep-reqs`

Thanks for helping us with this.

**Comment by dpoursanidis** [comment]
and in Processing it appear

![image](https://user-images.githubusercontent.com/8640644/231165287-c1ec80b2-88d0-4d01-b56d-9bf876806a54.png)

**Comment by biglimp** [comment]
So now it works but we dont know what was the issue in the first place...

**Comment by dpoursanidis** [comment]
> 

![image](https://user-images.githubusercontent.com/8640644/231166909-2095ed82-8ba4-4b88-a140-6c166e692755.png)

**Comment by dpoursanidis** [comment]
> no error?

no error in the console

**Comment by Inspire71** [comment]
I'm having the same installation problem, and I've followed the same steps shown in this conversation, but I'm getting an error the last installation of the pip install umep-reqs

**Comment by Inspire71** [comment]
The results of the installation are the following.
