### ISSUE TITLE
Issue with numformat2 variable in imagemorphparms_algorithm for SUEWS spatial tutorial

### ISSUE THREAD

**Issue by IvanHerreraCasas** [UMEP-dev/UMEP-processing#25]
Hi, I'm new to using QGIS and UMEP, and I'm encountering an error when following the [SUEWS spatial tutorial](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SuewsSpatial.html).

I am currently trying to run the building morphology algorithm, but I am receiving the following error message:

```
Traceback (most recent call last):   
File "C:\Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\preprocessor\imagemorphparms_algorithm.py", line 424, in processAlgorithm   fmt=numformat2, delimiter=' ', header=headerIso, comments='')   NameError: name 'numformat2' is not defined

Execution failed after 7.70 segundos
```

I am using QGIS version 3.30.1 and UMEP for processing version 2.0.1. I have followed the tutorial steps exactly and have not made any modifications.

Upon further investigation, I noticed that the `numformat2` variable seems to has been commented out in the [imagemorphparms_algorithm.py](https://github.com/UMEP-dev/UMEP-processing/blob/main/preprocessor/imagemorphparms_algorithm.py#:~:text=%23numformat2%20%3D%20%27%253d%20%254.3f%20%254.3f%20%255.3f%20%255.3f%20%255.3f%20%255.3f%20%255.3f%20%255.3f%27) file. It's not clear to me why this variable was commented out, and I suspect it might be the cause of the error.

**Comment by biglimp** [comment]
You are correct. Probably a misstake made by me when I updated this tool some time ago. Just uncomment the line where `numformat2` is defined, restart QGIS and try again. Please report back if this solves your problem.

**Comment by IvanHerreraCasas** [comment]
Hi, well I also had to uncomment headerIso, and seems that it solves the problem.
