### ISSUE TITLE
Urock not available when downloading the latest versions of QGIS and UMEP on MAcos

### ISSUE THREAD

**Issue by nicolascarnec** [UMEP-dev/UMEP-processing#26]
Hi, 

I would like to know if it is normal not to have access to URock while I just downloaded the latest versions of QGIS and UMEP on MAcos, see link of the picture (screen capture) below :
(https://user-images.githubusercontent.com/132055113/235104662-84cc251c-688d-4143-bb87-c2ec6371b444.png)
Thanks for your answer, 
Best regards, 
Nicolas Carnec, PHD student

**Comment by nilswallenberg** [comment]
Hi,

There are two versions of UMEP. One, which I think is the one you have in your screenshot, and one for the processing toolbox. URock is only available in the version for the processing toolbox. Check if you can find UMEP for processing and hopefully it works. :)

Cheers,
Nils

**Comment by nicolascarnec** [comment]
Hi ! 
You mean this one right ?
(https://user-images.githubusercontent.com/132055113/235111307-863ffccc-49c3-4caf-9a79-92d96abf662b.png)
As a matter of fact, before that I installed both just in case there was one plugin that was missing but as you could see it didn't work. Now, I've just tried to uninstall UMEP and install only "UMEP for processing" but I can't see any windows for UMEP in QGIS application anymore, as you can see below :/ 
(https://user-images.githubusercontent.com/132055113/235111717-32f2de29-1b09-45ea-bcdc-4f738f14fc2c.png)

**Comment by nilswallenberg** [comment]
Yes, that's good. Now you need to make your Processing Toolbox visible.
![processingToolbox](https://user-images.githubusercontent.com/33085509/235113145-08fe99e9-1e1b-46ff-baf9-b872e701b935.png)

**Comment by nicolascarnec** [comment]
That is perfect, thanks a lot for your quick answers !
