### ISSUE TITLE
Urock ==> version de pandas

### ISSUE THREAD

**Issue by bbrangeo** [UMEP-dev/UMEP-processing#29]
Bonjour, il faudrait modifier "iteritems" par "items".

<img width="1407" alt="Capture d’écran 2023-06-15 à 10 00 30" src="https://github.com/UMEP-dev/UMEP-processing/assets/769760/3f2c80e7-1926-4a9c-a227-93a64b344012">

Merci.

**Comment by j3r3m1** [comment]
done in #https://github.com/UMEP-dev/UMEP-processing/commit/621ba489501419bb4978c1e4970714dc4935459b

**Comment by bbrangeo** [comment]
Tks
