### ISSUE TITLE
Urock Analyzer output 

### ISSUE THREAD

**Issue by jessikalonn** [UMEP-dev/UMEP-processing#41]
Hi, 
I get a wierd output when i runt URock. I have a dummy area with a building running N-S and wind coming from SW. The building is 6m high:
![MicrosoftTeams-image](https://github.com/UMEP-dev/UMEP-processing/assets/111350166/d7a02b62-e6b3-4f75-8b49-a48bd96eb9c7)

I draw a line near the corner and the output shows wierd wind changes far above the building and the building divided in two:
![_line1](https://github.com/UMEP-dev/UMEP-processing/assets/111350166/805fb08e-01b4-4c29-bdef-b1446fb598a1)

When I run with vegetation i also dosn't seem to get the vegetation in the vertical wind profile.

Output folder:
[Urock.zip](https://github.com/UMEP-dev/UMEP-processing/files/12813188/Urock.zip)

Data used:

[URockDataIssue.zip](https://github.com/UMEP-dev/UMEP-processing/files/12813236/URockDataIssue.zip)

**Comment by j3r3m1** [comment]
Thank you for reporting.
The wind change is unfortunately more a URock calc problem than a URock analyze problem, coming from the rooftop corner scheme.
![image](https://github.com/UMEP-dev/UMEP-processing/assets/13120405/3629d540-e590-4fea-87d9-12c7e2fc03d6)
![image](https://github.com/UMEP-dev/UMEP-processing/assets/13120405/f45788d0-66c4-4988-8216-f42d7b826a14)

The building divided in two is a bug in the postprocessor. You should consider that there is a continuity of building (and I should consider fixing this in the future).

Concerning vegetation, it is not yet included in the vertical wind profile.

We might choose to turn off the postprocessing since it is not fully operational but in the mean time it is useful to identify bugs in the vertical extend...

**Comment by biglimp** [comment]
Thanks Jeremy. So the reason why the distortion to the profile is extended to unreasonable high height is because the building is "long". If we out the profile more in the middle it would look ok? 

Maybe we should just state that the URock Postprocessor is "under development"...

Off topic: Did you submit the article poofs?

**Comment by biglimp** [comment]
> > Thanks Jeremy. So the reason why the distortion to the profile is extended to unreasonable high height is because the building is "long". If we out the profile more in the middle it would look ok?
> 
> Yes. But in my opinion it shouldn't be a problem to have long building. The denominator of the Hccp equation should counter balance the yLp on the numerator. But I have not made a test for that (neither manually, neither in the code). First I would check the Equation and second the code if the equation is right. But no time right now...
> 
> > Maybe we should just state that the URock Postprocessor is "under development"...
> 
> Right ! Possible adding a flag in the QGIS plug-in ?
No, but some text to inform users. An experimental flag would be set fro the whole plugin and we dont want that.
> 
> > Off topic: Did you submit the article poofs?
> 
> I should resent, GMD cannot read my comments. Can you ?
No but I didnt check.

**Comment by biglimp** [comment]
Jessika, try to put line in the middle of the building.

**Comment by biglimp** [comment]
We have students that put the line in the middle of the building and it also produce strange output with a vertex that is many times higher than it should be.
![linje 270](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/314c9f85-b773-4b98-8e6c-00df07126e03)
![till fredrik 270_line1](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/108b122f-b72f-4a54-8d6f-d90ed77b6494)

**Comment by j3r3m1** [comment]
What is strange is the first layer of air above the roof. Can you do the simulation with a much smaller vertical resolution ? It seems you used something like 4 or five while your buildings are less than 5...

**Comment by biglimp** [comment]
More tests with a simpler setup:
![image](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/030848c5-7fad-4ecd-86f8-0c60f630213d)

[Modelinput.zip](https://github.com/UMEP-dev/UMEP-processing/files/12883289/Modelinput.zip)


1 meter resolution cannot produce plot (see other issue)

2 meter resolution
![11_line1](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/37dbbd13-9b36-4b8e-9bd4-b1047d9613ce)

4 meter resolution
![_line1](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/d29c05e7-fcf6-409a-9644-d04961b5e410)

**Comment by j3r3m1** [comment]
Thanks for reporting.
In my opinion results are consistent with what is expected by the models whenever the vertical resolution is lower than your building high. The rooftop zone is high but consistent with the Equation:
![image](https://github.com/UMEP-dev/UMEP-processing/assets/13120405/eec729a1-b9b6-44b8-8f00-0c9e029a8571)

Now if we have measurement evidence that the zone should be lower for large buildings we can of course update the scheme but first we need data illustrating it. I know the QUIC-URB developpers were working on updating their models dedicated to large buildings. We may adress this issue to them to know what their finding about it ?

**Comment by biglimp** [comment]
Ok, so the width and height of the building is giving this result? I increased the height of the building to 20 and there is still a rather large vortex above the building. Are you saying that if I had a building that is not so wide, the vortex would be lower? 

![image](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/8b27291c-3f38-432b-bab1-ed2a5b114512)

**Comment by j3r3m1** [comment]
There is no real vortex in this case above the buildings but a clear decrease of the wind speed for sure. And indeed if the building is less wide the vortex will be lower. Here is what we got for a square based building:
![image](https://github.com/UMEP-dev/UMEP-processing/assets/13120405/de44255e-19c0-4070-a873-91ff6a47a6a8)

**Comment by biglimp** [comment]
aha... then we have an explanation.
@jessikalonn and @nilswallenberg , note to us. See the dicussion above. Now we know why the votrex above our kindergarten is so high. MAybe we should make ti more squared for next year... I will close this now.

**Comment by j3r3m1** [comment]
Still it might be interesting to know more about the real wind for such large building since it seems the Röckle scheme is not quite appropriate for them and that it concerns quite de lot of buildings (at least in Sweden).
