### ISSUE TITLE
Request for Adding Functionality: Export Occurrence Map of TreePlanter

### ISSUE THREAD

**Issue by XiaoDONGDDDDDD** [UMEP-dev/UMEP-processing#42]
Dear Developers,

I would like to propose an enhancement for TreePlanter to include a new feature that allows users to export the occurrence maps for the random starting option by Hill-Climbing Algorithm. This feature would greatly benefit the analysis by sharing different data generated by the plugin.

Looking forward to it!

Best.
X

**Comment by nilswallenberg** [comment]
Hi Xiao,

I have not updated TreePlanter. Please try it out and see if it works as expected. :)

Cheers,
Nils

**Comment by nilswallenberg** [comment]
Great! :) I will close this now.
