### ISSUE TITLE
URock street canyon scheme update

### ISSUE THREAD

**Issue by j3r3m1** [UMEP-dev/UMEP-processing#45]
When using the street canyon scheme, two problems have been raised:
1. The initial wind speed within the canyon is not a function of the aspect ratio while a deep canyon should have wind speed close to 0.
2. The wind speed in the canyon might be affected by the size of the height of the downwind building. If the downstream building is higher than the upwind one, the wind speed in the canyon should be slightly increased while slightly decreased if it is lower.

For 1, I propose to multiply the current wind factors by $\frac{\frac{1}{H/W}^2}{1+\frac{1}{H/W}^2}$ and for 2 to multiply by $(1+\frac{0.6 dH}{H+0.6 dH})$ where H/W the aspect ratio of the canyon, H the height of the canyon and dH = Hdownstream-Hupstream.

I have the code for this version. I propose I push on my repo and you have a try with the zip file to see how it affect the results in your area ?

@biglimp

**Comment by j3r3m1** [comment]
Just as you know, the updated code is at my repo. Can you have a try and report ?

**Comment by biglimp** [comment]
Right. We should invite Janka. I need to get her Github ID. Hold on.

**Comment by j3r3m1** [comment]
@PythonJanus the new zip version can be downloaded [here](https://github.com/j3r3m1/UMEP-processing) for testing in QGIS.

**Comment by j3r3m1** [comment]
It has been included in https://github.com/UMEP-dev/UMEP-processing/commit/40e25ff6665cbe07fb29fc4be81f5e98b526c080.
It does not solve the problem met by @PythonJanus but it had to be done anyway.

The problem of large wind speed that sometimes happen within courtyards was actually related to cells being surrounded by 3 walls. In this case, the solver does not work well. A trick has been performed considering that these cells are buildings (cf. https://github.com/UMEP-dev/UMEP-processing/commit/0d0d353b6d972e60ce54fcae8cd1fcc4eddb3ba5).
