### ISSUE TITLE
SpatialTC ERROR

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#49]
### Discussed in https://github.com/UMEP-dev/UMEP/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **VladimirSobral** November 18, 2023</sup>
Hi,

I´m using spatial thermal comfort to generate a PET map but I had this message:

Traceback (most recent call last):
File "C:\Users/VLADIMIR/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep\postprocessor\spatialtc_algorithm.py", line 274, in processAlgorithm
yyyyTmrt = int(filepath_tmrt[-18:-14])
ValueError: invalid literal for int() with base 10: '_202'

Could anyone help me please?

Thanks
![pet](https://github.com/UMEP-dev/UMEP/assets/124792761/c0df5d71-8e3a-4225-b20c-5f8d597f52be)
</div>

**Comment by biglimp** [comment]
@VladimirSobral , please try the new code uploaded just now. Download as a zip and install in QGIS. Version 2.0.14.

**Comment by biglimp** [comment]
Go on the Code-tab in this repository and click on the green box saying Code. There you can find a link to download as zip.

**Comment by VladimirSobral** [comment]
Thanks for your quick reply. 
The process seems to work but I can't see the map.
Note I have an Output thermal comfort range (left) but no data in Results (upper right).

Would you know what´s wrong?

Thanks again.

![PET](https://github.com/UMEP-dev/UMEP-processing/assets/124792761/e1fc2977-e61e-4573-947a-bd2c034b9ad0)

**Comment by biglimp** [comment]
Please attach your Tmrt and wind speed raster

**Comment by VladimirSobral** [comment]
ok

[Nova pasta.zip](https://github.com/UMEP-dev/UMEP-processing/files/13415118/Nova.pasta.zip)

**Comment by biglimp** [comment]
I dont think there is anything wrong, except that you have a column of data (right) on your Tmrt-raster that is considerably lower that the rest of your data. If you scale your data (Layer Properties > Symbology) your should see the result.

**Comment by VladimirSobral** [comment]
Yes, when I created the DSM of my area, this column appeared. I couldn't fix it at the moment but I'll try to do it.
I'll let you know soon. Thank you so much! :)

**Comment by biglimp** [comment]
I am closing this issue as the error is not appearing. If you want further assistance/help, you can use the Discussion-forum again.
