### ISSUE TITLE
Different limits for clothing parameter in PET and SOLWEIG / SpatialTC functions

### ISSUE THREAD

**Issue by luise-wei** [UMEP-dev/UMEP-processing#60]
Hello,

I noticed a difference in the description of the value range for the clothing parameter for the PET index calculation. In SOLWEIG a range of 0-10 is given.
https://github.com/UMEP-dev/UMEP-processing/blob/77032d2db7e0df9e76b976ddb652506d27ed2a31/processor/solweig_algorithm.py#L256-L258
 
And in PET_calculations._PET function we see a range of 0-5 in the description of the input parameter for clothing for the _PET function. However, it is not checked whether the actual given clothing value complies with that described range.
https://github.com/UMEP-dev/UMEP-processing/blob/77032d2db7e0df9e76b976ddb652506d27ed2a31/functions/SOLWEIGpython/PET_calculations.py#L68
 
The code of PET differentiates clothing between values of <=0.3<=0.6<2
https://github.com/UMEP-dev/UMEP-processing/blob/77032d2db7e0df9e76b976ddb652506d27ed2a31/functions/SOLWEIGpython/PET_calculations.py#L133-L138

I don't know why the limits of clothing are set to 0-5 and 0-10 respectively nor how this affects the results of PET calculations. I could imagine that leads to an overestimation of PET as the clothing values in a range 0-10 are comparatively larger, when considered in a range 0-5, but I haven't looked into the details of PET and parameter coeffects. As the default value of clothing in SOLWEIG is 0.9 and I assume that most users use default values, I don't think this has caused any problems yet.
 
Note that the recently published SpatialTC tool also uses the SOLWEIG range of 0-10 for clothing. See here: 
https://github.com/UMEP-dev/UMEP-processing/blob/77032d2db7e0df9e76b976ddb652506d27ed2a31/postprocessor/spatialtc_algorithm.py#L163-L165

Perhaps you can take a look at the files and standardize the limit values to one or the other variant.

**Comment by biglimp** [comment]
This is probably something you can ignore. The clothing value is not dependent on that range and this is something that I must have put in without much thought. As clo-value is a measure of the amount of clothes, I guess that clo-value can be higher that 5 (e.g. when Joey in Friends put on all of Chandlers clothes) ;-)

**Comment by luise-wei** [comment]
Ah okay! Good to know and thanks for the quick reply 👍 
I'm closing this issue then.
