### ISSUE TITLE
Urock issue: simplifed vs generalised vectors

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP-processing#62]
When using building and vegetation vectors that have been simplified using the QGIS Simplify tool (Douglas-Peucker at 1.5m as recommended), the model fails to run, due to 

`org.locationtech.jts.geom.org.locationtech.jts.geom.TopologyException: org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 527356.9999999991 5252488.000000001, 527356.0637653562 5252487.063765359 ) and LINESTRING ( 527356.0659019575 5252487.06590196, 527355.9999999991 5252487.050577191 ) [ (527356.0659019573, 5252487.06590196, NaN) ]`

However, when the vectors are generalised (GRASS generalize tool, douglas, 1.5 max tolerance value), the model runs well. I'm using vertical and horizontal resolutions of 2m.

[error_log_simp_vs_gen.txt](https://github.com/UMEP-dev/UMEP-processing/files/13915370/error_log_simp_vs_gen.txt)

[urock_vectors_simplified_1.5m.zip](https://github.com/UMEP-dev/UMEP-processing/files/13915130/urock_vectors_simplified_1.5m.zip)
[urock_vectors_generalised_1.5m.zip](https://github.com/UMEP-dev/UMEP-processing/files/13915160/urock_vectors_generalised_1.5m.zip)

**Comment by j3r3m1** [comment]
Thanks for reporting. Can you share your input data (before simplification) ?

**Comment by bweeding** [comment]
[data_before_simplification.zip](https://github.com/UMEP-dev/UMEP-processing/files/13916163/data_before_simplification.zip)

**Comment by j3r3m1** [comment]
It seems the problem comes from the vegetation layer. Do you have the same problem using the vegetation without simplification (in the vegetation case, there is no real need to simplify it as the code is since the vegetation zones are the vegetation) ?

**Comment by bweeding** [comment]
Yes there are problems when I run with the unsimplified/generalised vegetation vector (see issue #59 ).

**Comment by j3r3m1** [comment]
In #59 the issue was related to the building shape for sure but I did not expect the vegetation to raise problem. I used the simplification only on the building data, the vegetation data remains identical. Do you have a problem if you use the any simplified building data and the initial vegetation data ? For wind direction = 355° ?

**Comment by j3r3m1** [comment]
up ? @bweeding

**Comment by bweeding** [comment]
Hi Jeremy, apologies for the late reply! 

Using the raw vegetation vector, URock ran successfully.
