### ISSUE TITLE
Urock: Processing issue

### ISSUE THREAD

**Issue by Swagata1998** [UMEP-dev/UMEP-processing#64]
I am trying to obtain wind speed using Urock plugin of QGIS. However, I am receiving an error message while doing my processing:
![QGIS_message](https://github.com/UMEP-dev/UMEP-processing/assets/148905762/81688c21-90dc-4741-97d3-d1892ae94bbb)

For the pre-processing I use : R_building_foot:  as the building footprint
Building raster DSM: Roseau DSM (3D+ground)
DEM: no input
Output vector file: R_building_height (column for building height: ROOF_HEIGHT)

Then I used this vector file as an input in processor

building polygon: R_building_height
building height field: ROOF_HEIGHT
With ither settings in default:  ![default_processor_settings](https://github.com/UMEP-dev/UMEP-processing/assets/148905762/89adc441-b3a2-479f-9ede-5724149605d7)

But I am receiving the error that I mentioned earlier.
Please help me,

These were my input parameters in Urock processor: 
'ATTENUATION_FIELD' : '', 'BUILDINGS' : 'D:\\My_Data\\Wind\\R_building_height.shp', 'HEIGHT_FIELD_BUILD' : 'ROOF_HEIGH', 'HORIZONTAL_RESOLUTION' : 2, 'INPUT_PROFILE_FILE' : '', 'INPUT_PROFILE_TYPE' : 0, 'INPUT_WIND_DIRECTION' : 45, 'INPUT_WIND_HEIGHT' : 10, 'INPUT_WIND_SPEED' : 10, 'LOAD_OUTPUT' : True, 'OUTPUT_FILENAME' : 'urock_output', 'RASTER_OUTPUT' : None, 'SAVE_NETCDF' : False, 'SAVE_RASTER' : True, 'SAVE_VECTOR' : True, 'UROCK_OUTPUT' : 'TEMPORARY_OUTPUT', 'VEGETATION' : None, 'VEGETATION_CROWN_BASE_HEIGHT' : '', 'VEGETATION_CROWN_TOP_HEIGHT' : '', 'VERTICAL_RESOLUTION' : 2, 'WIND_HEIGHT' : '1.5' }

**Comment by j3r3m1** [comment]
Thank you for reporting. Can you please execute the following in a Python console (it can be the QGIS one) ?

```python
import winreg
java_key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\JavaSoft\Java Development Kit")
current_version, _ = winreg.QueryValueEx(java_key, "CurrentVersion")
java_version_key = winreg.OpenKey(java_key, current_version)
javaPath, _ = winreg.QueryValueEx(java_version_key, "JavaHome")
print(javaPath)

**Comment by j3r3m1** [comment]
@Swagata1998 do you still meet the issue ?
