### ISSUE TITLE
Error when installing UMEP for processing

### ISSUE THREAD

**Issue by CDelasse** [UMEP-dev/UMEP-processing#68]
I need UMEP for processing to run the Sky View Factor module.
I got this error when I installed it :
ImportError: attempted relative import with no known parent package 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/cdelasse01/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP-processing-main\processing_umep.py", line 38, in 
    from .processing_umep_provider import ProcessingUMEPProvider
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: attempted relative import with no known parent package

Python Version : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS Version : 3.32.2-Lima Lima, c0b8833964 
Numpy Version : numpy-1.23.1

Thanks in advance

**Comment by biglimp** [comment]
Try updating your numpy version to at least 1.24 (https://umep-docs.readthedocs.io/en/latest/Getting_Started.html#adding-missing-python-libraries-and-other-osgeo-functionalities)

**Comment by CDelasse** [comment]
Tried it. Apparently it's incompatible with the version of scipy i have : ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.4 which is incompatible.

**Comment by biglimp** [comment]
Then you should update scipy also. Currently QGIS comes with scipy 1.10.1 and numpy 1.24.1. I recommend that you update scipy using the OsGeo4W setup

**Comment by CDelasse** [comment]
I updated scipy as you said, uninstalled then reinstalled the plugin "UMEP For processing", now I don't have that error anymore but I can't find the plugin in the menu even though I checked it in the list. Do you know where the problem could be?

**Comment by biglimp** [comment]
What list are you referring to? UMEP for Processing will not be found in the menubar but in the Processing Toolbox in QGIS:

![image](https://github.com/UMEP-dev/UMEP-processing/assets/11908356/de768bcd-7675-42f3-86c5-41c97e32ed24)

**Comment by CDelasse** [comment]
Okay, thank you
