### ISSUE TITLE
UMEP for processing and UMEP error installing

### ISSUE THREAD

**Issue by albmorsam** [UMEP-dev/UMEP-processing#80]
Hi,

 I am doing a master thesis at Lund university for the program energy efficient and environmental building design.

I try to learn QSIS following this tutotial

[Solar Energy - Introduction to SEBE — UMEP Tutorial documentation (umep-docs.readthedocs.io)](https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SEBE.html)

but i get error to download UMEP and UMEP for processing (see images below). do you know how to figure out? 

i try to install the plugin using the zip from github but I get same error about python ç8see below)

![1](https://github.com/UMEP-dev/UMEP-processing/assets/125660123/1fd19bc6-4a80-48b4-beb5-f3cd1e2a0c39)
![error UMEP](https://github.com/UMEP-dev/UMEP-processing/assets/125660123/49ab2f9e-d72f-46a9-89d2-a80335d43e4b)

**Comment by catodiaz** [comment]
Same issue #78 and probably related to issue #79. Something is not functional at the moment due to an Python update in QGIS.

**Comment by j3r3m1** [comment]
As @catodiaz said, if you want to use SEBE, I think your problem can be solved using the following python line in the QGIS Python console (go to plugin -> Python console):
```python
import pip
pip.main(['install', 'jaydebeapi'])
pip.main(['install', 'numba'])
pip.main(['install', 'xarray'])
pip.main(['install', 'netCDF4'])
```

**Comment by albmorsam** [comment]
I got this errors doing ot one by one. same problem I have unfortunately

import pip
pip.main(['install', 'jaydebeapi'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting jaydebeapi
  Downloading JayDeBeApi-1.2.3-py3-none-any.whl.metadata (10 kB)
Collecting JPype1 (from jaydebeapi)
  Downloading JPype1-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: packaging in c:\osgeo4w\apps\python312\lib\site-packages (from JPype1->jaydebeapi) (24.0)
Downloading JayDeBeApi-1.2.3-py3-none-any.whl (26 kB)
Downloading JPype1-1.5.0-cp312-cp312-win_amd64.whl (352 kB)
   ---------------------------------------- 352.2/352.2 kB 3.6 MB/s eta 0:00:00
Installing collected packages: JPype1, jaydebeapi
Successfully installed JPype1-1.5.0 jaydebeapi-1.2.3
0
pip.main(['install', 'numba'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting numba
  Downloading numba-0.59.1-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting llvmlite<0.43,>=0.42.0dev0 (from numba)
  Downloading llvmlite-0.42.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: numpy<1.27,>=1.22 in c:\osgeo4w\apps\python312\lib\site-packages (from numba) (1.26.4)
Downloading numba-0.59.1-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 2.7/2.7 MB 4.7 MB/s eta 0:00:00
Downloading llvmlite-0.42.0-cp312-cp312-win_amd64.whl (28.1 MB)
   ---------------------------------------- 28.1/28.1 MB 5.3 MB/s eta 0:00:00
Installing collected packages: llvmlite, numba
Successfully installed llvmlite-0.42.0 numba-0.59.1
0
pip.main(['install', 'xarray'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting xarray
  Using cached xarray-2024.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.23 in c:\osgeo4w\apps\python312\lib\site-packages (from xarray) (1.26.4)
Requirement already satisfied: packaging>=23.1 in c:\osgeo4w\apps\python312\lib\site-packages (from xarray) (24.0)
Requirement already satisfied: pandas>=2.0 in c:\osgeo4w\apps\python312\lib\site-packages (from xarray) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\osgeo4w\apps\python312\lib\site-packages (from pandas>=2.0->xarray) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\osgeo4w\apps\python312\lib\site-packages (from pandas>=2.0->xarray) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\osgeo4w\apps\python312\lib\site-packages (from pandas>=2.0->xarray) (2024.1)
Requirement already satisfied: six>=1.5 in c:\osgeo4w\apps\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0->xarray) (1.16.0)
Downloading xarray-2024.5.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 4.4 MB/s eta 0:00:00
Installing collected packages: xarray
Successfully installed xarray-2024.5.0
0
pip.main(['install', 'netCDF4'])
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: netCDF4 in c:\users\albert\appdata\roaming\python\python312\site-packages (1.6.5)
Requirement already satisfied: cftime in c:\users\albert\appdata\roaming\python\python312\site-packages (from netCDF4) (1.6.3)
Requirement already satisfied: certifi in c:\osgeo4w\apps\python312\lib\site-packages (from netCDF4) (2024.2.2)
Requirement already satisfied: numpy in c:\osgeo4w\apps\python312\lib\site-packages (from netCDF4) (1.26.4)
0

**Comment by j3r3m1** [comment]
I do not see any error in the results. If you close QGIS and reopen it do you still have an error ? You probably have UMEP for processing available in the toolbox so you should be able to use the plugin (except SUEWS maybe).

**Comment by albmorsam** [comment]
sorry, you right I don get the error when I open QGIS but , yes when I try to install the plugin UMPE for processing

![image](https://github.com/UMEP-dev/UMEP-processing/assets/125660123/f28d0f45-8723-4451-a43f-457a14c0aa70)

![image](https://github.com/UMEP-dev/UMEP-processing/assets/125660123/5c21ec1d-4416-414a-9941-7c3234cc66af)

**Comment by j3r3m1** [comment]
You can accept without the Python libraries installed. It is only if you want to use SUEWS that you will meet errors. It should be solved soon and does not avoid you to use the other processes of UMEP. Let us know if it works well.

**Comment by albmorsam** [comment]
ok thanks I am beginner to understand how this work  However I dont see the tab for UMEP for processing once I install it as I see when I do it with UMEP. Where can I find UMEP for processing in the interface QGIS?

**Comment by j3r3m1** [comment]
You should be able to find it in the toolbox interface (cf. https://docs.qgis.org/3.10/en/docs/user_manual/processing/intro.html#introduction)

**Comment by j3r3m1** [comment]
I close as it is complete and that the error you are still facing will be solved in an other issue
