### ISSUE TITLE
 UMEP > Post-Processor > Solar Radiation > SEBE (Visualisation).

### ISSUE THREAD

**Issue by albmorsam** [UMEP-dev/UMEP-processing#81]
Hi,

I follow this tutorial but I get an error when I do the visualization area. Do you know why? 

https://umep-docs.readthedocs.io/projects/tutorial/en/latest/Tutorials/SEBE.html

Ha ocurrido un error mientras se ejecutaba el código de Python: 

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "C:\Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SEBEVisual\tools\areaTool.py", line 107, in canvasMoveEvent
    self.areaRubberband1 = QgsRubberBand(self.canvas, False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

Versión de Python: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Versión de QGIS: 3.36.2-Maidenhead Maidenhead, 6d250527 

Ruta de Python:
C:\Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare/Modules
C:\Users\Albert\AppData\Roaming\Python\Python312\site-packages
C:\Users\Albert\AppData\Roaming\Python\Python312\site-packages
C:\Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umep
C:\Users\Albert\AppData\Roaming\Python\Python312\site-packages
C:\Users\Albert\AppData\Roaming\Python\Python312\site-packages
C:/OSGeo4W/apps/qgis/./python
C:/Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\Users\Albert\OneDrive - Lund University\Dokument
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\Users\Albert\AppData\Roaming\Python\Python312\site-packages
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Albert/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Albert/OneDrive - Lund University/Skrivbordet

Regards

**Comment by biglimp** [comment]
There seem to have been an update in the QgsRubberBand function. We will try to fix but it might be a while before we have time to look into this.

**Comment by biglimp** [comment]
This is now solved.
