### ISSUE TITLE
outlier in SEBE results running on a grid

### ISSUE THREAD

**Issue by ElishaGo** [UMEP-dev/UMEP-processing#85]
Hi,

I have a DSM I split by a grid (410*410 pixels, 0.5 meter pp), and run SEBE on each area in the grid using python multiprocessing.
In the resulting .tif files, some of the areas has extremely diferent result (min value is negative, -419). 
When I create another grid with different size of rectangles, I get this anomaly in different area.

Any Idea what can cause this?

Umep version 4.0.4 (8 Dec 2023)  
QGIS 3.36.2

Thank you,
Elisha
![anomaly_by_grid](https://github.com/user-attachments/assets/67e22206-83b1-4e91-8244-9ff76252034a)

**Comment by biglimp** [comment]
Hm, starge. Could there be some NoData-values that are present in some of the grids? I assume you are using the same metfile for all the grids.
